export {
  collectEmbeddableAssets,
  collectReferencedAssetIds,
  getAssetMimeType,
  getBundleAssetKey,
  indexProjectAssets,
  resolveAssetSource,
  resolveFilesystemAssetPath,
  resolveImageHref,
  resolveProjectAssetMap,
  shouldEmbedAsset,
} from './assets.ts'
export {
  applyEasing,
  evaluateColorValue,
  evaluateNumericValue,
  mixColor,
  parseHexColor,
} from './animation.ts'
export {
  decodeProjectBundleBuffer,
  decodeProjectContainer,
  encodeLegacyProjectContainer,
  encodeProjectBundle,
  isLegacyProjectContainer,
} from './container.ts'
export {
  evaluateLayerForRender,
  evaluateProjectSceneState,
  evaluateSceneBackground,
  evaluateSceneLayers,
  getActiveScene,
  getSceneBackground,
  getSceneProgress,
  getTransitionProgress,
  isLayerVisibleAtSceneTime,
} from './evaluate.ts'
export {
  decodeProjectBundle,
  parseProject,
  parseProjectJson,
  readProjectFromPath,
  serializeProject,
  writeProjectFile,
} from './project.ts'
export {
  createSampleProject,
  encodeProjectToContainer,
  getPrimaryAudioAsset,
  loadProjectForRender,
  renderFrame,
  renderFrameSvg,
  renderSvgToPng,
} from './render.ts'
export {
  assetSchema,
  colorStringSchema,
  easingSchema,
  groupLayerSchema,
  imageLayerSchema,
  layerSchema,
  sceneSchema,
  sceneTransitionSchema,
  shapeLayerSchema,
  textLayerSchema,
  textVideoProjectSchema,
  vec2Schema,
} from './schema.ts'
export {
  buildFontString,
  ensureNodeMeasurementBackend,
  layoutTextLayer,
  loadPretextModule,
  registerProjectFonts,
} from './text.ts'
export type {
  AnimatedNumber,
  AnimatedString,
  AudioAsset,
  Easing,
  FontAsset,
  GroupLayer,
  ImageAsset,
  ImageLayer,
  Layer,
  Point2D,
  SceneTransition,
  ShapeLayer,
  TextLayer,
  TextPadding,
  TextShadow,
  TextStroke,
  TextVideoAsset,
  TextVideoProject,
  TextVideoScene,
} from './schema.ts'
export type {
  AssetResolutionContext,
  BundleAssetPayload,
  DecodedProjectContainer,
  EmbeddedAssetRecord,
  EvaluatedGroupLayer,
  EvaluatedImageLayer,
  EvaluatedLayer,
  EvaluatedLayerBase,
  EvaluatedShapeLayer,
  EvaluatedTextLayer,
  LoadedProject,
  PretextModule,
  RenderFrameOptions,
  RenderFrameResult,
  RenderedTextBlock,
  ResolvedAssetSource,
  SceneRenderState,
} from './types.ts'
