import { textVideoProjectSchema, type TextVideoProject } from './schema.ts'

export function createSampleProject(): TextVideoProject {
  return textVideoProjectSchema.parse({
    format: 'pretext-text-video',
    version: 2,
    info: {
      name: 'sample-text-video',
      description: 'A modular semantic motion graphics sample powered by Pretext.',
      author: 'Adam Hofmann',
    },
    video: {
      width: 1920,
      height: 1080,
      fps: 30,
      durationSeconds: 8,
      background: '#07111d',
    },
    assets: [
      {
        id: 'font-sans',
        type: 'font',
        family: 'DejaVu Sans',
        src: '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
      },
      {
        id: 'font-serif',
        type: 'font',
        family: 'DejaVu Serif',
        src: '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',
      },
      {
        id: 'openai-mark',
        type: 'image',
        src: 'pages/assets/openai-symbol.svg',
        embed: true,
        mimeType: 'image/svg+xml',
      },
      {
        id: 'claude-mark',
        type: 'image',
        src: 'pages/assets/claude-symbol.svg',
        embed: true,
        mimeType: 'image/svg+xml',
      },
    ],
    scenes: [
      {
        id: 'intro',
        start: 0,
        duration: 4,
        background: {
          keyframes: [
            { time: 0, value: '#07111d' },
            { time: 4, value: '#0a1d2f', easing: 'ease-in-out' },
          ],
        },
        transitionIn: { type: 'fade', duration: 0.6, easing: 'ease-in-out' },
        layers: [
          {
            id: 'backdrop',
            type: 'shape',
            shape: 'rect',
            x: 92,
            y: 92,
            width: 1736,
            height: 896,
            fill: '#0f172a',
            radius: 40,
            opacity: { keyframes: [{ time: 0, value: 0.3 }, { time: 1.2, value: 0.8, easing: 'ease-out' }] },
          },
          {
            id: 'logo-group',
            type: 'group',
            x: 1410,
            y: 130,
            children: [
              {
                id: 'openai',
                type: 'image',
                assetId: 'openai-mark',
                x: 0,
                y: 0,
                width: 220,
                height: 220,
                opacity: { keyframes: [{ time: 0.2, value: 0 }, { time: 1.3, value: 1, easing: 'ease-out' }] },
                rotation: { keyframes: [{ time: 0, value: -8 }, { time: 2.5, value: 8, easing: 'ease-in-out' }] },
                fit: 'contain',
                anchorX: 'center',
                anchorY: 'center',
              },
              {
                id: 'claude',
                type: 'image',
                assetId: 'claude-mark',
                x: 240,
                y: 40,
                width: 180,
                height: 180,
                opacity: { keyframes: [{ time: 0.4, value: 0 }, { time: 1.5, value: 1, easing: 'ease-out' }] },
                fit: 'contain',
                anchorX: 'center',
                anchorY: 'center',
              },
            ],
          },
          {
            id: 'eyebrow',
            type: 'text',
            text: 'PRETEXT VIDEO ENGINE',
            fontFamily: 'DejaVu Sans',
            fontWeight: 700,
            fontSize: 32,
            lineHeight: 40,
            width: 700,
            x: { keyframes: [{ time: 0, value: 138 }, { time: 1.2, value: 170, easing: 'ease-out' }] },
            y: 118,
            color: '#7dd3fc',
            letterSpacing: 4,
            opacity: { keyframes: [{ time: 0, value: 0.15 }, { time: 1.2, value: 1, easing: 'ease-in' }] },
          },
          {
            id: 'headline',
            type: 'text',
            text: {
              keyframes: [
                { time: 0, value: 'Render semantic motion graphics from editable source.' },
                { time: 2.2, value: 'Render semantic motion graphics from editable source.' },
              ],
            },
            fontFamily: 'DejaVu Serif',
            fontWeight: 700,
            fontSize: { keyframes: [{ time: 0, value: 74 }, { time: 2.8, value: 94, easing: 'ease-in-out' }] },
            lineHeight: { keyframes: [{ time: 0, value: 88 }, { time: 2.8, value: 108, easing: 'ease-in-out' }] },
            width: { keyframes: [{ time: 0, value: 1120 }, { time: 2.5, value: 1280, easing: 'ease-out' }] },
            x: 140,
            y: 210,
            color: '#f8fafc',
            shadow: {
              color: '#020617',
              blur: 16,
              offsetX: 0,
              offsetY: 8,
              opacity: 0.65,
            },
          },
          {
            id: 'body',
            type: 'text',
            text: 'This engine stores scenes, layers, animation, and assets semantically. Pretext handles line layout; SVG keeps output crisp; MP4 stays a derived export instead of the source of truth.',
            fontFamily: 'DejaVu Sans',
            fontSize: 34,
            lineHeight: 50,
            width: 900,
            x: 150,
            y: { keyframes: [{ time: 0, value: 682 }, { time: 2.8, value: 620, easing: 'ease-out' }] },
            color: '#cbd5e1',
            opacity: { keyframes: [{ time: 0.4, value: 0 }, { time: 1.8, value: 1, easing: 'ease-in' }] },
            background: { keyframes: [{ time: 0, value: '#0f172a' }, { time: 3, value: '#132238' }] },
            padding: { top: 20, right: 24, bottom: 20, left: 24 },
            cornerRadius: 18,
          },
        ],
      },
      {
        id: 'feature-grid',
        start: 4,
        duration: 4,
        background: '#091a2a',
        transitionIn: { type: 'slide-left', duration: 0.8, easing: 'ease-in-out' },
        layers: [
          {
            id: 'hero-copy',
            type: 'group',
            x: 120,
            y: 120,
            children: [
              {
                id: 'hero-title',
                type: 'text',
                text: 'Customizable, layered, and bundle-aware.',
                fontFamily: 'DejaVu Serif',
                fontWeight: 700,
                fontSize: 76,
                lineHeight: 92,
                width: 1100,
                x: 0,
                y: 0,
                color: '#ffffff',
              },
              {
                id: 'hero-subtitle',
                type: 'text',
                text: 'Text, shapes, images, groups, keyframes, transitions, and embedded assets are all first-class.',
                fontFamily: 'DejaVu Sans',
                fontSize: 34,
                lineHeight: 50,
                width: 980,
                x: 6,
                y: 220,
                color: '#dbeafe',
              },
            ],
          },
          {
            id: 'cards',
            type: 'group',
            x: 120,
            y: 520,
            children: [
              {
                id: 'card-a',
                type: 'shape',
                shape: 'rect',
                x: 0,
                y: 0,
                width: 520,
                height: 260,
                fill: '#10233a',
                radius: 28,
              },
              {
                id: 'card-a-copy',
                type: 'text',
                text: 'Bundle local fonts and artwork into a portable .ptxv archive.',
                fontFamily: 'DejaVu Sans',
                fontWeight: 700,
                fontSize: 32,
                lineHeight: 46,
                width: 440,
                x: 36,
                y: 36,
                color: '#f8fafc',
              },
              {
                id: 'card-b',
                type: 'shape',
                shape: 'rect',
                x: 580,
                y: 0,
                width: 520,
                height: 260,
                fill: '#12324d',
                radius: 28,
              },
              {
                id: 'card-b-copy',
                type: 'text',
                text: 'Drive a browser studio preview with the same schema used for offline rendering.',
                fontFamily: 'DejaVu Sans',
                fontWeight: 700,
                fontSize: 32,
                lineHeight: 46,
                width: 438,
                x: 616,
                y: 36,
                color: '#f8fafc',
              },
            ],
          },
        ],
      },
    ],
  })
}
